language: node_js
node_js:
  - "10"
cache: yarn
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
script:
  - yarn lint
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app:
    master: espm-david-server
